openapi: 3.0.0

info:
  title: "RPaaS API"
  description: "This file specification describes the web API of the Reverse Proxy as a Service."
  version: 0.4.0
  contact:
    name: "Tsuru PaaS"
    email: tsuru@corp.globo.com
    url: "https://github.com/tsuru/rpaas"
    
paths:
  /admin/plugin:
    get:
      summary: "Returns a Tsuru plugin to manage the RPaaS service through the command line interface."
      tags:
      - plugins
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: string

  /plugin:
    get:
      summary: "Returns a Tsuru plugin to use the RPaaS service through the command line interface"
      tags:
      - plugins
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: string
